display_errors = On
error_reporting = E_ALL
upload_max_filesize = 64M
post_max_size = 64M
date.timezone = Europe/Zurich

; mail() envoie vers Mailpit
sendmail_path = "/usr/bin/msmtp -t --host=mailpit --port=1025 --from=noreply@localhost"
